### PR TITLE
Test Gpu OC

### PR DESCRIPTION
**Pull request by VlikeBanana**

### CODE REVIEW

**Comment by hellsgod** [comment]
I've tested it. Seems to work, but there are some things I don't like at it. First 487mhz is set as default (I don't want to OC anything on my device) and second there are instabilities with OC, like green screen in the camera, kernel panics and so on. I don't need that. Compile another two versions only for OC is not in my interest. Thanks for your effort, but it's nothing for me atm.

**Comment by VlikeBanana** [comment]
Did you add In defconfig :
CONFIG_GPU_OVERCLOCK=y ?
Could you upload the kernel  ?

**Comment by hellsgod** [comment]
Of course it was added and seems to work, because max gpu clock was at 487mhz. You have a lucky day, because I dont have deleted the zImage ;) Here you have the Zip: https://www.dropbox.com/s/bgb4j7y1q05y9mb/hells-Core_b37-t1-AOSP_4.3_anykernel.zip

But keep in mind, it was the first and last kernel with gpu oc atm.

**Comment by VlikeBanana** [comment]
Thank you :) 
No problem, its your kernel and work :)
If I want it so hard I can add it myself !
May I use your kernel as basement for mine ? I will give you full credits !

**Pull request merged**
